
      const App = ({ url }) => {
          const posts = Array.from({ length: 50 }).map((_, i) => ({ id: i, title: 'Post ' + (i + 1) }));
          return '<div><h1>Sparx SSR Web Blog</h1><p>Current Path: <strong data-testid="url-display">' + url + '</strong></p><ul>' + 
                 posts.map(p => '<li>' + p.title + '</li>').join('') + '</ul></div>';
      };
      exports.render = async function(context) {
          const html = App({ url: context.url });
          const head = '<title>SSR Blog</title><meta name="description" content="Generated by Sparx SSR">';
          const state = { url: context.url, posts: 50 };
          return { html, head, state };
      };
    